### ISSUE TITLE
@doc and @moduledoc in Exercises overwhelming for beginner

### ISSUE THREAD

**Issue by srgarner** [DockYard-Academy/curriculum#629] opened 2022-11-23 21:50 UTC
Hello Brooklin, 
Elixir newbie, and overall programming newbie here. I just wanted to give feedback for the course so far. I've made it through to Comprehensions in the last week. I'm learning so very much but I think often times, the exercises are quite challenging as a beginner and combine concepts that I simply find myself having to look up and sometimes feeling like they lack relevance or maybe believability as a work use case (ie: rock, paper, scissors, lizard, spock)

In any case, the one that feels like a big slap in the face every time, is the long lines of documentation and iex testing written and giving several errors because of unfinished code. Because of this I have skipped several exercises and its been kind of demotivating.
I understand that it's an important to learn for being part of a team and professionally, but as someone who is still trying to grasp even the basic programming concepts, practice idiomatic syntax and get the functional programming philosophy it is quite overwhelming.

Suggestions:
-Perhaps documentation and test cases should be introduced in a separate box away from the code-- similar to how it was done in the "Replacing nil" Drill following the Comprehensions and Non-Enumerables section. 
-Maybe it can be more seriously implemented once the basic types and all commonly used modules are covered? 
-Or we can get more chance/prompts to practice writing the docs in our own code to feel more comfortable with it and be able to better digest it.
-ALSO... I like more chances to practice syntax on smaller tasks which build up to building apps/games. I love it when it's "Your Turn" :)

Thanks,
Steve G

**Comment by BrooklinJazz** [comment] 2022-11-29 02:47
Hi Steve, thank you for the feedback!

> the exercises are quite challenging as a beginner and combine concepts that I simply find myself having to look up

We provide example solutions to help unblock students. Without the classroom environment it's a lot easier to get stuck on exercises because you don't have a teacher/classmates present. Googling is absolutely normal and expected.

>  and sometimes feeling like they lack relevance or maybe believability as a work use case (ie: rock, paper, scissors, lizard, spock)

I agree with you that not every exercise feels "real". It's tough to accomplish, especially early in the course when students have very few tools available. I'm 100% open to exercise suggestions. That said, I think Rock Paper Scissors is a very real use case. It's a perfect example of control flow and at the end of it, you have a working game. It could even be the basis for a phoenix web application that allows users to play against each other.

> In any case, the one that feels like a big slap in the face every time, is the long lines of documentation and iex testing written and giving several errors because of unfinished code. Because of this I have skipped several exercises and its been kind of demotivating...Perhaps documentation and test cases should be introduced in a separate box away from the code-- similar to how it was done in the "Replacing nil" Drill following the Comprehensions and Non-Enumerables section.

Livebook only recently released the feature to run doctests inside of Livebook. Your frustration is understandable. We have to review the material and find places where it causes friction. Ideally, failing tests shouldn't cause the code to crash (but it currently does in many places as we haven't adjusted for the recent change). If you encounter these problems, please raise an issue or make a PR to address the issue.

We use doctests to get students familiar with reading them, to make the expectations of the exercise clear, and also as a convenient way to provide immediate feedback. If you find the large doctests cumbersome, you can collapse them inside of the editor to hide them. 

We don't want to use ExUnit tests or move the tests for several reasons.
1. It's easy for different cells to get out of sync, which can cause confusion.
2. ExUnit is not covered until later in the course.
3. The doctests provide the student with immediate feedback if they made a mistake.

To resolve this issue, I'm planning to review the existing doctests, simplify them where possible, and find any spots that are likely to cause an error and convert them into documentation instead of a doctest.

> Or we can get more chance/prompts to practice writing the docs in our own code to feel more comfortable with it and be able to better digest it.

I'd like to revamp our "doctest" section now that doctests run in Livebook. That opens a lot more options for potential exercises.

Hope you found those answers satisfying! Thank you for your input. 🙏

**Comment by srgarner** [comment] 2022-11-29 22:39
Wow, thank you soo much for taking the time to address my concerns. It really shows a lot of care and I appreciate the effort. I realized that I was just trying to grab the syntax and breeze through to be able to build something as fast as possible.
I think I will slow it down and try to digest the basics a bit more.

But still seeking to learn as much as I can. I really want to get into development and really eager to learn Elixir/Phoenix and all they have to offer.
Hopefully, I can get enough understanding to even contribute to this awesome project in some small way :).

Keep up the good work!

**Comment by BrooklinJazz** [comment] 2022-12-02 19:44
Thank you Steve! I'm happy to, you've helped reveal some gaps in the curriculum and I look forward to addressing them :) 

I would love to see a PR! There are lots of opportunities. We mark [Issues](https://github.com/DockYard-Academy/beta_curriculum/issues) as "good first issue" for those that are hopefully beginner friendly.

The doctests should **almost never** crash on an empty solution (however, we can't avoid crashes caused by student solutions at the moment). If you encounter this, it would help a lot if you raise an issue with a quick screenshot. 🙏

I'm also happy to do a 30min 1-1 session to walk you through how to make a PR and contribute to the project if that's something you're not already familiar with. :)

**Comment by BrooklinJazz** [comment] 2023-01-23 02:13
I've done some work to improve docs where possible. However, it's a tough balance between thorough testing and readability.
I'm leaning more towards ensuring tests catch student errors because students can hide the documentation if they find it verbose.

There are still some places left with large doc tests, but we can address those on an individual case-by-case basis, so I'm closing this issue for now. If you find any documentation you think can be removed, please make an issue for the exercise so we can track them individually.

Thank you again for the feedback!

**Closed by BrooklinJazz** 2023-01-23 02:13 UTC
