### ISSUE TITLE
(Comment on this to vote) Let's create a Discord server (or else) for contributors to fast discussion and ideation

### ISSUE THREAD

**Issue by amir-repository** [DockYard-Academy/curriculum#860] opened 2023-03-02 21:43 UTC
I think we need a fast-moving room for discussion with other contributors, and maybe there's a crazy idea that we could discuss or just get to know each other and be friends

**Comment by BrooklinJazz** [comment] 2023-03-02 22:28
Now I'm scared 😅

I'd like to mention some of our contributors to see if there's interest.

@Billboz @BigSpaces @matt-humphrey @Mraiih @threetriangles @SRFowler @waranlogesh @mvkvc @lgmfred @padmaJS @miguelbermudez @drueck @zorn @byronsalty @matt-humphrey @czrpb @IciaCarroBarallobre @paulo-valim @auranykh @crismxiex @aar2dee2 @TheGriffinCircus @aroojahmad

**Comment by crismxiex** [comment] 2023-03-02 23:12
It could also be a channel on an existing server.

**Comment by mvkvc** [comment] 2023-03-02 23:13
Down for another server but if everyone is already in DYA or Elixir Newbie maybe just create a collab text/voice channel that is open to everyone.

**Comment by TheGriffinCircus** [comment] 2023-03-02 23:41
The DYA server would probably streamline it under one umbrella.  The only issue is for self-led like myself the server might need to be tweaked to allow both students and self-led on it.

**Comment by lgmfred** [comment] 2023-03-02 23:55
I'm more in line with Cris, Marko and Williams's idea(s).

**Comment by BrooklinJazz** [comment] 2023-03-02 23:59
I agree, if we made a group I would make on the DYA Discord.

We could have a contributor role and contributor only chats. I'll also have to make some slight modifications so that student-only channels are protected.

It would also be interesting if we could get github integration on Discord 🤔

**Comment by crismxiex** [comment] 2023-03-03 00:01
If you need any help with discord let me know

**Comment by zorn** [comment] 2023-03-03 00:04
Not 100% percent sure what is being asked for. Chat spaces for discussion can work, though they lean on a more synchronous-style than I usually experience/prefer in open-source contributions. I would throw out GitHub Dicussions as a feature/space to talk about curriculum improvements or suggestions outside of PRs if you wanted to turn that on. 🤷‍♂️

https://docs.github.com/en/discussions

Honestly, I'm not actively doing much work here, so do what you will with the suggestion.

**Comment by BrooklinJazz** [comment] 2023-03-03 00:06
Would we want to create some regular event(s) to get contributors together and plan some tasks? I can think of a few useful activities. We won't do them all, just brainstorming.

- Regression Testing and tracking issues
- working on tickets
- planning tickets and reporting progress
- helping first timers make PRs

**Comment by BrooklinJazz** [comment] 2023-03-03 00:11
> Not 100% percent sure what is being asked for. Chat spaces for discussion can work, though they lean on a more synchronous-style than I usually experience/prefer in open-source contributions. I would throw out GitHub Dicussions as a feature/space to talk about curriculum improvements or suggestions outside of PRs if you wanted to turn that on. 🤷‍♂️
> 
> https://docs.github.com/en/discussions
> 
> Honestly, I'm not actively doing much work here, so do what you will with the suggestion.

Very valid point and part of why I want to see if others do or don't want this. Open source is often a low pressure async activity and I like it that way.

Do other people think like they would really use a Discord chat for making contributions?

**Comment by byronsalty** [comment] 2023-03-03 00:21
I think I'm with @zorn in trying to understand the value vs using the DYA existing Discord for comms. I'm happy to get involved in however this shakes out though. I'm with @BrooklinJazz in that I hope this ends up mostly low-key and async.

**Comment by mvkvc** [comment] 2023-03-03 00:55
The easiest thing IMO is to create another text channel in DYA ex. `#contrib` for async and the existing `Public` channel for sync. I don't think it implies any commitment and people can drop in and out as they wish.

**Comment by loteks** [comment] 2023-03-03 16:04
Awesome idea! I think linking this with DYA presents a great opportunity for us noobies to get started contributing with access to help/mentoring as we learn and I agree that a #contrib channel makes the most sense.

**Comment by tindrew** [comment] 2023-03-03 16:26
I'd love to contribute. I'd say definitely link it to DYA existing discord instead of making a completely new discord. Also While maybe using github discussions could be useful, I think more people are likely to have discord open or pay attention to chats there than relying on notifications from github. Worst case make a channel on the DYA discord and see how it shakes out? It costs nothing to make a channel.

**Comment by SRFowler** [comment] 2023-03-03 23:19
Between the D&D level scheduling conflicts that would prevent real time contribution, the requirement that the curriculum remain somewhat static during an active cohort, and the lack of a real necessity to have large coordinated projects to rework Dockyard Academy I personally don't see a need for a dedicated space to facilitate high bandwidth discussion.

**Comment by opanye** [comment] 2023-03-04 04:22
Jumping in here mostly to express interesting in contributing. But! I will echo others in saying that simply adding a dedicated channel to the existing DYA server makes most sense to me. Also: many folks may not be able to e.g. attend weekend meetups, so primarily asynchronous info exchange may be preferable...but it would be good to have a dedicated DYA contributor Voice Channel that people could log onto at any given time to discuss things with anybody else who happens to be online. This would be especially useful for early-stage developers.

**Comment by Billboz** [comment] 2023-03-06 15:38
An argument for having a DYA space is to incentivize and provide a place for support for new programmers to participate in contributing to the DYA curriculum and getting the general experience of working with shared repos. 
 Having a space for contributors to communicate about the steps of contribution, to debate on how to contribute to GitHub discussions, and about early thoughts on improving the curriculum seems enough to start one and see how it goes.
 I think a DYA space for contributors is outside of GitHub discussions since it ideally would support and guide new programmers to use GitHub discussions properly and where useful.

**Comment by 0xmohsinpathan** [comment] 2023-03-06 20:55
Yes, I like to contribute

**Comment by paulo-valim** [comment] 2023-03-08 07:27
I'm in as well! =D

**Comment by auranykh** [comment] 2023-03-09 20:30
A bit late to the party but I'm interested! I don't have a lot of time to contribute at the moment but I'd love to help with new ideas and chip in where I can.

**Comment by matt-humphrey** [comment] 2023-03-09 22:20
I’d also love to be involved :)
________________________________

**Comment by Mraiih** [comment] 2023-03-09 22:26
I'll be glad to help as well :)

**Comment by BrooklinJazz** [comment] 2023-03-14 05:49
Thank you all for your thoughts!

After hearing everyone's input, I've decided using the Elixir Newbie discord is best to start. You can join here:
https://discord.gg/kJSpkjhCb7 (link expires in 7 days - message me if you need another) See the #dya-contributors channel for the forum we'll use to organize discussions.

If this group is successful, we can consider moving it to the DYA Discord in the future.

We're going to run weekly sessions Sunday at 9 am PT in the General voice channel. I look forward to seeing you all there.

**Closed** 2023-05-30 06:49 UTC
