### ISSUE TITLE
Something is bad please check this

### ISSUE THREAD

**Issue by 0xmohsinpathan** [DockYard-Academy/curriculum#819] opened 2023-02-21 16:57 UTC
**Describe the issue**
A clear and concise description of the issue.

**Reproduction Steps (If Applicable)**

**Expected behavior**

**Screenshots**

**Comment by BrooklinJazz** [comment] 2023-02-23 05:57
Hey @0xmohsinpathan What is this issue for? The issue is empty. closing for now.

**Closed by BrooklinJazz** 2023-02-23 05:57 UTC
